//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVEData.Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppEvent : Event
    {
        public string ProcessHandle { get; set; }
        public string ProcessName { get; set; }
        public string ProcessPath { get; set; }
        public string WindowTitle { get; set; }
        public string AppType { get; set; }
        public bool IsActive { get; set; }
        public string CommandLine { get; set; }
    }
}
