//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVEData.Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebuggerEvent : Event
    {
        public string Mode { get; set; }
        public string Reason { get; set; }
        public string Action { get; set; }
    }
}
