//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVEData.Tools
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int EventId { get; set; }
        public int SessionId { get; set; }
        public int InFileId { get; set; }
        public int SequenceId { get; set; }
        public string Type { get; set; }
        public string Details { get; set; }
        public Nullable<System.DateTime> TriggeredAt { get; set; }
        public Nullable<long> TimeStamp { get; set; }
        public string TriggeredBy { get; set; }
        public string Duration { get; set; }
        public string ActiveDocumentName { get; set; }
        public string ActiveDocumentType { get; set; }
        public string ActiveWindowCaption { get; set; }
        public string ActiveWindowType { get; set; }
        public string Result { get; set; }
    
        public virtual Session Session { get; set; }
    }
}
